const copy = {
  "en": {
    "pub.widistill.alt": "WiDistill framework: random sampling, expert trajectory generation, and trajectory matching",
    "pub.first": "First author",
    "pub.widistill": "Dataset distillation with trajectory matching for efficient training and cross-user generalization in Wi-Fi sensing.",
    "pub.paper": "Paper",
    "pub.figure": "Figure",
    "pub.awn.alt": "Adaptive Wavelet Network architecture with multi-level decomposition and attention",
    "pub.second": "Second author",
    "pub.awn": "Automatic modulation classification through multi-level wavelet decomposition and attention.",
    "pub.amc.alt": "AMC-Net architecture with adaptive correction, multi-scale, and feature fusion modules",
    "pub.amc": "Automatic modulation classification with adaptive correction, multi-scale features, and feature fusion.",
    "edu.ut.alt": "The University of Tokyo logo",
    "edu.ut.title": "The University of Tokyo",
    "edu.ut.date": "Oct. 2026 to Oct. 2028 (expected)",
    "edu.ut.degree": "M.S. in Information Science and Technology",
    "edu.ut.dept": "Department of Information Physics and Computing",
    "edu.xdu.alt": "Xidian University emblem",
    "edu.xdu.title": "Xidian University",
    "edu.xdu.date": "Sep. 2020 to Jul. 2024",
    "edu.xdu.degree": "B.Eng. in Artificial Intelligence, Turing Program",
    "edu.xdu.detail": "Selected among 40 students from 1,450 undergraduates. GPA: 3.7/4.0.",
    "exp.e1.title": "Human-centered robotics and human-computer interaction",
    "exp.e1.place": "The University of Tokyo",
    "exp.e1.body": "Multimodal perception, shared autonomy, robotic augmentation, and adaptive human-machine collaboration.",
    "exp.e2.title": "Multimodal human sensing and activity recognition",
    "exp.e2.body": "Wi-Fi CSI, wearable IMUs, computer vision, human identification, 3D pose estimation, and dataset distillation.",
    "exp.e3.title": "RF signal processing and machine learning",
    "exp.e3.place": "Key Laboratory of Intelligent Perception and Image Understanding",
    "exp.e3.body": "Deep learning and time-frequency representations for robust automatic modulation classification.",
    "nav.publications": "Publications",
    "nav.education": "Education",
    "nav.experience": "Experience",
    "nav.awards": "Awards",
    "nav.blog": "Notes",
    "bio1": "I am an M.S. student at the University of Tokyo, in the Department of Information Physics and Computing. I received my B.Eng. in Artificial Intelligence from Xidian University, where I was part of the Turing Program.",
    "bio2": "My research interests include human-centered robotics, multimodal sensing, and machine learning. I work with Wi-Fi CSI, wearable IMUs, and vision to understand human activity. Previously, I studied RF signal processing and automatic modulation classification.",
    "pub.title": "Selected publications",
    "exp.title": "Research experience",
    "award.context.alt": "Competition background chart showing strain sensitivity versus gravitational-wave frequency for pulsars",
    "award.context.caption": "Scientific background figure from the competition overview.",
    "award.medal": "Silver medal",
    "award.body": "45th out of 936 teams (top 5%), 2023",
    "award.brief": "The competition focused on detecting weak, long-lasting gravitational-wave signals from rapidly spinning neutron stars in noisy data. This search could help scientists understand the structure of these extreme stars.",
    "award.organizer": "Hosted on Kaggle by the European Gravitational Observatory.",
    "award.link": "Competition",
    "award.evidence": "View medal result",
    "award.result.alt": "Kaggle result: silver medal, team placed 45th out of 936 teams",
    "award.result.caption": "Kaggle result: silver medal, 45th out of 936 teams.",
    "blog.body": "I keep a small archive of older posts about learning and everyday life.",
    "blog.button": "Read the old blog",
    "footer.back": "Back to top"
  },
  "ja": {
    "pub.widistill.alt": "WiDistill の構成：ランダムサンプリング、エキスパート軌跡生成、軌跡マッチング",
    "pub.first": "筆頭著者",
    "pub.widistill": "軌跡マッチングによるデータセット蒸留を用い、Wi-Fiセンシングの学習効率とユーザ間汎化性能を向上。",
    "pub.paper": "論文",
    "pub.figure": "構成図",
    "pub.awn.alt": "多段階分解と注意機構を備えた適応ウェーブレットネットワークの構成",
    "pub.second": "第二著者",
    "pub.awn": "多段階ウェーブレット分解と注意機構による自動変調識別。",
    "pub.amc.alt": "適応補正、マルチスケール、特徴融合モジュールを備えた AMC-Net の構成",
    "pub.amc": "適応補正、マルチスケール特徴、特徴融合による自動変調識別。",
    "edu.ut.alt": "東京大学のロゴ",
    "edu.ut.title": "東京大学",
    "edu.ut.date": "2026年10月から2028年10月（予定）",
    "edu.ut.degree": "情報理工学 修士課程",
    "edu.ut.dept": "情報理工学系研究科 システム情報学専攻",
    "edu.xdu.alt": "西安電子科技大学の校章",
    "edu.xdu.title": "西安電子科技大学",
    "edu.xdu.date": "2020年9月から2024年7月",
    "edu.xdu.degree": "人工知能 工学学士、Turing Program",
    "edu.xdu.detail": "学部生1,450名から40名に選抜。GPA: 3.7/4.0。",
    "exp.e1.title": "人間中心ロボティクスとヒューマンコンピュータインタラクション",
    "exp.e1.place": "東京大学",
    "exp.e1.body": "マルチモーダル知覚、共有自律、ロボットによる能力拡張、人と機械の適応的協働。",
    "exp.e2.title": "マルチモーダル人間センシングと行動認識",
    "exp.e2.body": "Wi-Fi CSI、IMU、画像、個人識別、3D姿勢推定、データセット蒸留。",
    "exp.e3.title": "RF信号処理と機械学習",
    "exp.e3.place": "知能感知・画像理解教育部重点実験室",
    "exp.e3.body": "深層学習と時間周波数表現を用いた頑健な自動変調識別。",
    "nav.publications": "論文",
    "nav.education": "学歴",
    "nav.experience": "研究経験",
    "nav.awards": "受賞",
    "nav.blog": "ノート",
    "bio1": "東京大学大学院情報理工学系研究科システム情報学専攻の修士課程に在籍しています。西安電子科技大学のTuring Programで人工知能を学び、工学学士を取得しました。",
    "bio2": "研究の関心は、人間中心ロボティクス、マルチモーダルセンシング、機械学習です。Wi-Fi CSI、ウェアラブルIMU、画像を用いた人の行動理解に取り組んでいます。これまでにRF信号処理と自動変調識別を研究しました。",
    "pub.title": "主要論文",
    "exp.title": "研究経験",
    "award.context.alt": "コンペティションの背景図：パルサーの重力波ひずみ感度と周波数の関係",
    "award.context.caption": "コンペティション概要に掲載された科学的背景の図。",
    "award.medal": "銀メダル",
    "award.body": "936チーム中45位（上位5%）、2023年",
    "award.brief": "高速回転する中性子星が放出する微弱で長時間持続する重力波信号を、ノイズの多いデータから検出するコンペティションです。この探索は、極限状態にある星の内部構造の理解につながると期待されています。",
    "award.organizer": "欧州重力観測所がKaggleで開催。",
    "award.link": "コンペティション",
    "award.evidence": "受賞結果を見る",
    "award.result.alt": "Kaggle の結果：銀メダル、936 チーム中 45 位",
    "award.result.caption": "Kaggleの結果：銀メダル、936チーム中45位。",
    "blog.body": "学習や日常について書いた以前の記事をアーカイブとして残しています。",
    "blog.button": "以前のブログを読む",
    "footer.back": "ページの先頭へ"
  },
  "zh": {
    "pub.widistill.alt": "WiDistill 框架：随机采样、专家轨迹生成与轨迹匹配",
    "pub.first": "第一作者",
    "pub.widistill": "通过轨迹匹配进行数据集蒸馏，提高 Wi-Fi 感知的训练效率与跨用户泛化能力。",
    "pub.paper": "论文",
    "pub.figure": "结构图",
    "pub.awn.alt": "自适应小波网络架构，包含多层分解与注意力机制",
    "pub.second": "第二作者",
    "pub.awn": "结合多层小波分解与注意力机制的自动调制识别方法。",
    "pub.amc.alt": "AMC-Net 架构，包含自适应校正、多尺度与特征融合模块",
    "pub.amc": "结合自适应校正、多尺度特征与特征融合的自动调制识别方法。",
    "edu.ut.alt": "东京大学校徽",
    "edu.ut.title": "东京大学",
    "edu.ut.date": "2026年10月至2028年10月（预计）",
    "edu.ut.degree": "信息科学与技术硕士",
    "edu.ut.dept": "信息物理与计算系",
    "edu.xdu.alt": "西安电子科技大学校徽",
    "edu.xdu.title": "西安电子科技大学",
    "edu.xdu.date": "2020年9月至2024年7月",
    "edu.xdu.degree": "人工智能工学学士，图灵班",
    "edu.xdu.detail": "从 1,450 名本科生中选拔 40 人。GPA：3.7/4.0。",
    "exp.e1.title": "以人为中心的机器人与人机交互",
    "exp.e1.place": "东京大学",
    "exp.e1.body": "多模态感知、共享自主、机器人增强与自适应人机协作。",
    "exp.e2.title": "多模态人体感知与行为识别",
    "exp.e2.body": "Wi-Fi CSI、可穿戴 IMU、计算机视觉、身份识别、3D 姿态估计与数据集蒸馏。",
    "exp.e3.title": "RF 信号处理与机器学习",
    "exp.e3.place": "智能感知与图像理解教育部重点实验室",
    "exp.e3.body": "基于深度学习与时频表示的鲁棒自动调制识别。",
    "nav.publications": "论文",
    "nav.education": "教育经历",
    "nav.experience": "研究经历",
    "nav.awards": "获奖",
    "nav.blog": "随笔",
    "bio1": "我在东京大学信息理工学系研究科系统信息学专攻攻读硕士。本科毕业于西安电子科技大学人工智能专业，就读于图灵班。",
    "bio2": "我的研究兴趣包括以人为中心的机器人、多模态感知和机器学习。目前主要利用 Wi-Fi CSI、可穿戴 IMU 和视觉理解人体行为，此前研究过 RF 信号处理与自动调制识别。",
    "pub.title": "代表性论文",
    "exp.title": "研究经历",
    "award.context.alt": "比赛背景图：脉冲星的引力波应变灵敏度与引力波频率关系",
    "award.context.caption": "比赛介绍中的科学背景图。",
    "award.medal": "银牌",
    "award.body": "936 支队伍中排名第 45（前 5%），2023年",
    "award.brief": "比赛的目标是从噪声数据中识别高速旋转中子星发出的微弱、持续时间长的引力波信号。这项搜寻有望帮助科学家进一步了解这些极端天体的内部结构。",
    "award.organizer": "由欧洲引力波天文台在 Kaggle 举办。",
    "award.link": "比赛主页",
    "award.evidence": "查看获奖截图",
    "award.result.alt": "Kaggle 获奖结果：银牌，936 支队伍中排名第 45",
    "award.result.caption": "Kaggle 比赛结果：银牌，936 支队伍中排名第 45。",
    "blog.body": "这里保留了一些关于学习和日常生活的旧文章。",
    "blog.button": "阅读旧博客",
    "footer.back": "返回顶部"
  }
};

function setLang(requestedLang) {
  const lang = Object.hasOwn(copy, requestedLang) ? requestedLang : 'en';
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const value = copy[lang][el.dataset.i18n];
    if (value) el.textContent = value;
  });
  document.querySelectorAll('[data-i18n-alt]').forEach(el => {
    const value = copy[lang][el.dataset.i18nAlt];
    if (value) el.alt = value;
  });
  document.querySelectorAll('.lang-switch button').forEach(button => {
    const active = button.dataset.lang === lang;
    button.classList.toggle('active', active);
    button.setAttribute('aria-pressed', String(active));
  });
}

document.querySelectorAll('.lang-switch button').forEach(button => {
  button.addEventListener('click', () => setLang(button.dataset.lang));
});

// Always open in English. Language buttons change only the current page view.
setLang('en');
document.getElementById('year').textContent = new Date().getFullYear();
