const copy = {
  "en": {
    "nav.about": "About",
    "nav.research": "Research",
    "nav.publications": "Publications",
    "nav.experience": "Experience",
    "nav.education": "Education",
    "nav.blog": "Notes",
    "hero.eyebrow": "Academic Homepage",
    "hero.role": "M.S. Student · The University of Tokyo",
    "hero.summary": "I work on human-centered robotics, multimodal sensing, and machine learning, with an interest in building systems that understand people and collaborate with them naturally.",
    "hero.publications": "Publications",
    "hero.location": "Tokyo, Japan",
    "focus.robotics": "Human-Centered Robotics",
    "focus.sensing": "Multimodal Sensing",
    "focus.ml": "Machine Learning",
    "focus.hci": "HCI",
    "about.title": "Researching intelligent systems around people.",
    "about.p1": "I am an M.S. student at the University of Tokyo. My current research explores multimodal sensing and learning for understanding human motion, intention, and physical states, together with human-centered robotics, shared autonomy, and robotic augmentation.",
    "about.p2": "Previously, I worked on multimodal human sensing with Wi-Fi CSI, wearable IMUs, and computer vision, as well as RF signal processing and automatic modulation classification with deep learning.",
    "research.title": "Research directions",
    "research.subtitle": "My work connects perception, learning, and interaction.",
    "research.r1.title": "Human-Centered Robotics",
    "research.r1.body": "Human-robot interaction, shared autonomy, and robotic augmentation for adaptive and intuitive collaboration.",
    "research.r2.title": "Multimodal Human Sensing",
    "research.r2.body": "Combining Wi-Fi CSI, wearable IMUs, and vision to recognize activities, identities, pose, and physical states.",
    "research.r3.title": "Machine Learning for Signals",
    "research.r3.body": "Learning efficient and robust representations for wireless and RF signals under real-world channel and noise conditions.",
    "pub.title": "Selected publications",
    "pub.subtitle": "Publications and preprints listed in my CV.",
    "pub.widistill": "Dataset distillation and trajectory matching for improving training efficiency and cross-user generalization in large-scale Wi-Fi sensing.",
    "exp.title": "Research experience",
    "exp.e1.title": "Human-Centered Robotics & Human-Computer Interaction",
    "exp.e1.place": "The University of Tokyo",
    "exp.e1.body": "Multimodal perception, shared autonomy, robotic augmentation, and adaptive human-machine collaboration.",
    "exp.e2.title": "Multimodal Human Sensing & Activity Recognition",
    "exp.e2.body": "Wi-Fi CSI, wearable IMUs, computer vision, human identification, 3D pose estimation, and dataset distillation.",
    "exp.e3.title": "RF Signal Processing & Machine Learning",
    "exp.e3.place": "Key Laboratory of Intelligent Perception and Image Understanding",
    "exp.e3.body": "Deep learning and time-frequency representations for robust automatic modulation classification.",
    "edu.ut.title": "The University of Tokyo",
    "edu.ut.degree": "M.S. in Information Science and Technology",
    "edu.ut.dept": "Department of Information Physics and Computing",
    "edu.xdu.title": "Xidian University",
    "edu.xdu.degree": "B.Eng. in Artificial Intelligence, Turing Program",
    "edu.xdu.detail": "Selected among 40 students from 1,450 undergraduates · GPA 3.7/4.0",
    "award.title": "Competition award",
    "award.body": "Silver Medal · 45th of 936 teams · Top 5%",
    "blog.title": "Older writing, kept as an archive.",
    "blog.body": "My previous Hexo posts remain available as a small personal archive.",
    "blog.button": "View old archive →",
    "footer.text": "Academic homepage · Tokyo",
    "pub.figure": "View full-size figure ↗",
    "pub.widistill.alt": "WiDistill framework: random sampling, expert trajectory generation, and trajectory matching",
    "pub.awn.alt": "Adaptive Wavelet Network architecture with multi-level decomposition and attention",
    "pub.amc.alt": "AMC-Net architecture with adaptive correction, multi-scale, and feature fusion modules",
    "edu.ut.alt": "The University of Tokyo logo",
    "edu.xdu.alt": "Xidian University emblem",
    "award.organizer": "Kaggle · European Gravitational Observatory (EGO) · 2023",
    "award.medal": "Silver Medal",
    "award.result.alt": "Kaggle result: silver medal, team placed 45th out of 936 teams",
    "award.result.caption": "Competition result — Silver Medal, 45 / 936 teams. Select the image to view it full size.",
    "award.goal.title": "Goal of the competition",
    "award.goal": "Detect weak, long-lasting gravitational-wave signals emitted by rapidly spinning neutron stars in noisy data. The competition challenges participants to develop models sensitive enough to identify these continuous signals.",
    "award.context.title": "Scientific context",
    "award.context": "Neutron stars pack a mass comparable to the Sun into a city-sized object. Searching for their continuous gravitational waves could reveal new insights into the structure of these extreme stars and help broaden gravitational-wave astronomy.",
    "award.link": "View competition ↗",
    "award.context.alt": "Competition background chart showing strain sensitivity versus gravitational-wave frequency for pulsars",
    "award.context.caption": "Scientific background figure from the competition overview: strain sensitivity versus gravitational-wave frequency."
  },
  "ja": {
    "nav.about": "プロフィール",
    "nav.research": "研究",
    "nav.publications": "論文",
    "nav.experience": "研究経験",
    "nav.education": "学歴",
    "nav.blog": "ノート",
    "hero.eyebrow": "研究者ホームページ",
    "hero.role": "東京大学 修士課程",
    "hero.summary": "人間中心ロボティクス、マルチモーダルセンシング、機械学習を中心に、人を理解し自然に協働できる知能システムの研究に取り組んでいます。",
    "hero.publications": "論文",
    "hero.location": "東京、日本",
    "focus.robotics": "人間中心ロボティクス",
    "focus.sensing": "マルチモーダルセンシング",
    "focus.ml": "機械学習",
    "focus.hci": "HCI",
    "about.title": "人を中心に据えた知能システムの研究。",
    "about.p1": "東京大学の修士課程に在籍しています。現在は、人の動作・意図・身体状態を理解するためのマルチモーダルセンシングと学習手法に加え、人間中心ロボティクス、共有自律、ロボットによる能力拡張を研究しています。",
    "about.p2": "これまでに、Wi-Fi CSI、ウェアラブルIMU、コンピュータビジョンを用いた人間センシング、ならびに深層学習によるRF信号処理と自動変調識別に取り組みました。",
    "research.title": "研究テーマ",
    "research.subtitle": "知覚・学習・インタラクションをつなぐ研究を行っています。",
    "research.r1.title": "人間中心ロボティクス",
    "research.r1.body": "適応的で直感的な協働を目指したHRI、共有自律、ロボットによる能力拡張。",
    "research.r2.title": "マルチモーダル人間センシング",
    "research.r2.body": "Wi-Fi CSI、IMU、画像を組み合わせ、行動・個人・姿勢・身体状態を認識。",
    "research.r3.title": "信号のための機械学習",
    "research.r3.body": "実環境のチャネルやノイズに頑健な無線・RF信号表現の学習。",
    "pub.title": "主要論文",
    "pub.subtitle": "CVに記載している論文・プレプリントです。",
    "pub.widistill": "大規模Wi-Fiセンシングデータに対して、データセット蒸留とTrajectory Matchingにより学習効率とユーザ間汎化性能を向上。",
    "exp.title": "研究経験",
    "exp.e1.title": "人間中心ロボティクス・HCI",
    "exp.e1.place": "東京大学",
    "exp.e1.body": "マルチモーダル知覚、共有自律、ロボットによる能力拡張、人と機械の適応的協働。",
    "exp.e2.title": "マルチモーダル人間センシング・行動認識",
    "exp.e2.body": "Wi-Fi CSI、IMU、画像、個人識別、3D姿勢推定、データセット蒸留。",
    "exp.e3.title": "RF信号処理・機械学習",
    "exp.e3.place": "知能感知・画像理解教育部重点実験室",
    "exp.e3.body": "深層学習と時間周波数表現を用いた頑健な自動変調識別。",
    "edu.ut.title": "東京大学",
    "edu.ut.degree": "情報理工学 修士課程",
    "edu.ut.dept": "情報理工学系研究科 システム情報学専攻",
    "edu.xdu.title": "西安電子科技大学",
    "edu.xdu.degree": "人工知能 工学学士・Turing Program",
    "edu.xdu.detail": "学部生1,450名から40名に選抜 · GPA 3.7/4.0",
    "award.title": "コンペティション受賞",
    "award.body": "銀メダル · 936 チーム中 45 位 · 上位 5%",
    "blog.title": "以前の文章はアーカイブとして残しています。",
    "blog.body": "旧Hexoブログの記事を個人的な記録として閲覧できます。",
    "blog.button": "旧アーカイブを見る →",
    "footer.text": "Academic homepage · Tokyo",
    "pub.figure": "元のサイズで図を見る ↗",
    "pub.widistill.alt": "WiDistill の構成：ランダムサンプリング、エキスパート軌跡生成、軌跡マッチング",
    "pub.awn.alt": "多段階分解と注意機構を備えた適応ウェーブレットネットワークの構成",
    "pub.amc.alt": "適応補正、マルチスケール、特徴融合モジュールを備えた AMC-Net の構成",
    "edu.ut.alt": "東京大学のロゴ",
    "edu.xdu.alt": "西安電子科技大学の校章",
    "award.organizer": "Kaggle · 欧州重力観測所（EGO）· 2023",
    "award.medal": "銀メダル",
    "award.result.alt": "Kaggle の結果：銀メダル、936 チーム中 45 位",
    "award.result.caption": "コンペティション結果：銀メダル、45 / 936 チーム。画像を選択すると元のサイズで表示します。",
    "award.goal.title": "コンペティションの目標",
    "award.goal": "高速回転する中性子星が放出する、微弱で長時間持続する重力波信号をノイズの多いデータから検出することが目標です。参加者は、こうした連続重力波信号を識別できる高感度なモデルの開発に取り組みます。",
    "award.context.title": "科学的背景",
    "award.context": "中性子星は、太陽に匹敵する質量が都市ほどの大きさに凝縮した天体です。その連続重力波を探すことで、極限状態にある星の内部構造への理解が深まり、重力波天文学の観測の幅が広がると期待されています。",
    "award.link": "コンペティションを見る ↗",
    "award.context.alt": "コンペティションの背景図：パルサーの重力波ひずみ感度と周波数の関係",
    "award.context.caption": "コンペティション概要に掲載された科学的背景の図：重力波ひずみ感度と周波数の関係。"
  },
  "zh": {
    "nav.about": "关于",
    "nav.research": "研究",
    "nav.publications": "论文",
    "nav.experience": "研究经历",
    "nav.education": "教育经历",
    "nav.blog": "随笔",
    "hero.eyebrow": "个人学术主页",
    "hero.role": "东京大学 · 硕士研究生",
    "hero.summary": "我的研究聚焦于以人为中心的机器人、多模态感知与机器学习，希望构建能够理解人并与人自然协作的智能系统。",
    "hero.publications": "论文",
    "hero.location": "日本 · 东京",
    "focus.robotics": "以人为中心的机器人",
    "focus.sensing": "多模态感知",
    "focus.ml": "机器学习",
    "focus.hci": "人机交互",
    "about.title": "研究围绕人的智能系统。",
    "about.p1": "我目前在东京大学攻读硕士学位。当前研究包括用于理解人体运动、意图与身体状态的多模态感知与学习方法，以及以人为中心的机器人、共享自主和机器人增强。",
    "about.p2": "此前我主要研究基于 Wi-Fi CSI、可穿戴 IMU 与计算机视觉的多模态人体感知，以及结合深度学习的 RF 信号处理与自动调制识别。",
    "research.title": "研究方向",
    "research.subtitle": "我的工作连接感知、学习与交互。",
    "research.r1.title": "以人为中心的机器人",
    "research.r1.body": "面向自适应、直观协作的人机交互、共享自主与机器人增强。",
    "research.r2.title": "多模态人体感知",
    "research.r2.body": "融合 Wi-Fi CSI、可穿戴 IMU 和视觉，实现行为、身份、姿态与身体状态识别。",
    "research.r3.title": "面向信号的机器学习",
    "research.r3.body": "学习在真实信道和噪声条件下高效、鲁棒的无线与 RF 信号表示。",
    "pub.title": "代表性论文",
    "pub.subtitle": "以下为简历中列出的论文和预印本。",
    "pub.widistill": "面向大规模 Wi-Fi 感知数据，通过数据集蒸馏与轨迹匹配提升训练效率和跨用户泛化能力。",
    "exp.title": "研究经历",
    "exp.e1.title": "以人为中心的机器人与人机交互",
    "exp.e1.place": "东京大学",
    "exp.e1.body": "多模态感知、共享自主、机器人增强与自适应人机协作。",
    "exp.e2.title": "多模态人体感知与行为识别",
    "exp.e2.body": "Wi-Fi CSI、可穿戴 IMU、计算机视觉、身份识别、3D 姿态估计与数据集蒸馏。",
    "exp.e3.title": "RF 信号处理与机器学习",
    "exp.e3.place": "智能感知与图像理解教育部重点实验室",
    "exp.e3.body": "基于深度学习与时频表示的鲁棒自动调制识别。",
    "edu.ut.title": "东京大学",
    "edu.ut.degree": "信息科学与技术硕士",
    "edu.ut.dept": "信息物理与计算系",
    "edu.xdu.title": "西安电子科技大学",
    "edu.xdu.degree": "人工智能工学学士 · 图灵班",
    "edu.xdu.detail": "从1,450名本科生中选拔40人 · GPA 3.7/4.0",
    "award.title": "竞赛获奖",
    "award.body": "银牌 · 936 支队伍中排名第 45 · 前 5%",
    "blog.title": "旧文章作为个人档案保留。",
    "blog.body": "之前 Hexo 博客中的文章会继续作为个人记录保留。",
    "blog.button": "查看旧文章 →",
    "footer.text": "Academic homepage · Tokyo",
    "pub.figure": "查看高清原图 ↗",
    "pub.widistill.alt": "WiDistill 框架：随机采样、专家轨迹生成与轨迹匹配",
    "pub.awn.alt": "自适应小波网络架构，包含多层分解与注意力机制",
    "pub.amc.alt": "AMC-Net 架构，包含自适应校正、多尺度与特征融合模块",
    "edu.ut.alt": "东京大学校徽",
    "edu.xdu.alt": "西安电子科技大学校徽",
    "award.organizer": "Kaggle · 欧洲引力波天文台（EGO）· 2023",
    "award.medal": "银牌",
    "award.result.alt": "Kaggle 获奖结果：银牌，936 支队伍中排名第 45",
    "award.result.caption": "比赛成绩：银牌，45 / 936。点击图片可查看高清原图。",
    "award.goal.title": "比赛目标",
    "award.goal": "从噪声数据中检测高速旋转的中子星发出的微弱、持续时间长的引力波信号。参赛者需要开发足够灵敏的模型，识别这些连续引力波信号。",
    "award.context.title": "科学背景",
    "award.context": "中子星将与太阳相当的质量压缩在一座城市大小的空间中。搜寻其发出的连续引力波，有望帮助科学家了解这些极端天体的内部结构，并拓展引力波天文学的观测范围。",
    "award.link": "查看比赛 ↗",
    "award.context.alt": "比赛背景图：脉冲星的引力波应变灵敏度与引力波频率关系",
    "award.context.caption": "比赛介绍中的科学背景图：引力波应变灵敏度与引力波频率的关系。"
  }
};

function setLang(requestedLang) {
  const lang = Object.hasOwn(copy, requestedLang) ? requestedLang : 'en';
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const value = copy[lang][el.dataset.i18n];
    if (value) el.textContent = value;
  });
  document.querySelectorAll('[data-i18n-alt]').forEach(el => {
    const value = copy[lang][el.dataset.i18nAlt];
    if (value) el.alt = value;
  });
  document.querySelectorAll('.lang-switch button').forEach(button => {
    const active = button.dataset.lang === lang;
    button.classList.toggle('active', active);
    button.setAttribute('aria-pressed', String(active));
  });
}

document.querySelectorAll('.lang-switch button').forEach(button => {
  button.addEventListener('click', () => setLang(button.dataset.lang));
});

// Always open in English. Language buttons change only the current page view.
setLang('en');
document.getElementById('year').textContent = new Date().getFullYear();
